### ISSUE TITLE
Improve the explanation of displaying more than one collection or data resource

### ISSUE THREAD

**Issue by PB-GNM** [opengeospatial/ogcapi-maps#122]
As a reaction to the call for public comment on [ogc-api-maps-part-1-core-candidate-standard ](https://www.ogc.org/requests/ogc-seeks-public-comment-on-ogc-api-maps-part-1-core-candidate-standard/), we would like to suggest improvements on how to display more than one collection in one view.

In paragraph 6.2, it states: “One of the most significant use cases for the definition of the Maps API is the ability to generate maps on the web from one or more servers that can be combined into a single view”. For me it is clear how to combine 2 resources in a GIS-application, but what would be the request in a browser to combine them?
Is this what is meant in paragraph 10.2? Here it is not clear what is meant with requirement 9 and what the purpose is. It states: “When this parameter refers to more than one geospatial data resource, this parameter will use the comma (",") as the separator between the resource identifiers in the list”. Is this meant for requesting more than one resource in one map? Maybe an example how to use this parameter in one query would help understanding.

Regards,
Pieter Bresters,
Geonovum

**Comment by joanma747** [comment]
"combined" should be replaced by "overlaid".

How to do this from 2-3 servers in the client side (6.2). You can do it in the server side in (10.2) .../map?collections=buildings,roads,...

**Comment by jerstlouis** [comment]
@PB-GNM Correct, if dataset maps were implemented.

Unfortunately, at this point I am not aware of any implementation supporting the `collections`. We will try to include a mocked up example for now.

As for our own demonstration service, we also planned to support `collections=` on hierarchical collections, which we are likely to implement before the _Dataset maps_, since we host several mostly unrelated datasets from the same API root.

For example, we will try to implement the following soon for demonstration purposes):

https://maps.gnosis.earth/ogcapi/collections/NaturalEarth?collections=raster:HYP_HR_SR_OB_DR,physical:ne_10m_lakes

**Comment by joanma747** [comment]
An example of the request was added in section 10.

A mention of "collections section" was mentioned in the overview.
