### ISSUE TITLE
Can we use full URLs for CRS or abbreviations?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-maps#15]
Features CRS extension uses Full CRS but we are using abbreviations. It seems that full URLS are considered ids. It might be better to use full URLs instead

**Comment by jerstlouis** [comment]
The OGC NA policy on short-hand CURIEs forms of CRS URIs was applied this week ( https://github.com/opengeospatial/NamingAuthority/issues/92 and https://github.com/opengeospatial/NamingAuthority/issues/93 ).

See https://docs.opengeospatial.org/pol/09-048r6.html#toc23 .

We should include text explicitly allowing CURIEs as short-hand for full URIs in _OGC API - Maps_.

**Comment by jerstlouis** [comment]
The policy describint the use of CURIEs is at https://docs.opengeospatial.org/pol/09-048r6.html#toc14 .
Currently it mentions:

> OGC Standards should only allow [safe CURIEs](https://www.w3.org/TR/curie/#P_safe_curie), unless support for other forms of CURIEs is inherited from another standard

Not sure what the value of safe CURIE is if there is no way that a non-safe CURIE could be misinterpreted?

Safe CURIE would force us to use:

https://example.org/foo/collections/bar/map?crs=[EPSG:3395]

instead of

https://example.org/foo/collections/bar/map?crs=EPSG:3395

**Comment by jerstlouis** [comment]
It seems that the requirements in the specification should be that the server shall supprot safe CURIEs, but we should include a permission that the server may also be tolerant and interpret unsafe CURIE, which would be compatible with the WMS `crs=EPSG:4326` syntax.

**Comment by joanma747** [comment]
I'm not sure that adding a "[" "]" makes a string more safe :-). In any case I'm starting to see this very confusing. Too many notations for the same thing only because we are trying to please too many people: the old WMS users, the NA people and the RDF people.

**Comment by jerstlouis** [comment]
@joanma747 

> The square brackets may be used to prevent ambiguities between CURIEs and regular URIs, yielding so-called safe CURIEs.

from https://en.wikipedia.org/wiki/CURIE

See also https://www.w3.org/TR/curie/#sec_2.2 _2.2. Ambiguities Between CURIEs and URIs_

>  Too many notations for the same thing only because we are trying to please too many people:

Yes, the requirements would express that servers shall support the two following options:

- http://www.opengis.net/def/crs/EPSG/0/4326
- `[EPSG:4326]`

and a permission would allow them to also recognize simply `EPSG:4326`.

I feel it is good if we can make everybody happy ;)

**Comment by chris-little** [comment]
Can `EPSG:4326` cause wrong HTTP  and namespace behaviour, outside of a geospatial context?

**Comment by jerstlouis** [comment]
@chris-little I don't believe so currently, but as @cportele points out in https://github.com/opengeospatial/ogcapi-features/issues/632#issuecomment-1319086200 new URI schemes are added all the time.

**Comment by chris-little** [comment]
@jerstlouis My preference is for the Naming Authority policy (safe CURIEs) to remain. I think putting square brackets is not burdensome, is simple, and clearly avoids ambiguity. I see many examples of geospatial software using them, even doubled, to avoid ambiguity in a WKT context, such as optionally supporting arrays rather than single values. 
I am sympathetic to syntaxes and notation being global, generic and non-domain specific.
Safe CURIEs like `[`EPSG:nnnn]` is apolicy, so I suppose implementations are free to choose to be more generous, but I think Postel's Rule applies: accept generously, generate strictly.

**Comment by joanma747** [comment]
Applied and closed in regular telco
