### ISSUE TITLE
Other dimensions, time and elevation at several levels.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-maps#16]
the pattern:
\coverages\{coverageId}\map\{styleId}\tiles\...
allows for 3 approaches:

A:
WMTS extra dimentions (including time) in tiles
B: 
dimensions (including time and elevation) in maps
C:
slice the coverage dimensions in a way that generate a 2D coverage that is converted in a map that is converted in tiles.

That is gonna be?. The "C" reduces redundancy but might be too complex for simple users?

**Comment by jerstlouis** [comment]
This issue seems duplicated by #79 (with more discussions there) and also related to #53.

In terms of conformance classes defined in Maps - Part 1: Core, I think we want `bbox`, `datetime` and `subset` as mechanisms to subset both spatial and temporal dimensions as part of separate spatial and temporal subsetting conformance classes.

Currently it seems that "bbox" is tied in within the "Scaling" conformance class in Section 10 at the moment, but Section 2 Conformanec agrees that it should be its own conformance class.

**Comment by joanma747** [comment]
"bbox" is no longer tied with the "Scaling"

**Comment by joanma747** [comment]
New Conformance class for extra dimensions

* how to use subset in other dimensions
* where the dimension names can be found: in the collection description document. In an implementation of the extent there is an object that will enumerate property names (that are actually dimension names) and each of the should follow the same schema indicated in "additionalProperties".

Add a recommendation that "if the data is gridded, include the grid property". If the grid is irregular you implement "coordinates". It the grid is regular you implement cellsCount and resolution.

**Comment by joanma747** [comment]
Accepted with a clarification on how to use more than one subset.
