### ISSUE TITLE
New proposed structure for OGC API Maps

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-maps#32]
Hi,

In line with the proposed new structure for OGC API tiles  (https://github.com/opengeospatial/OGC-API-Tiles/issues/41), we propose the following OGC API Maps structure. Here we have to consider that we should apply a style to the map to get a styled map.
1.1 Map resource
It specifies a map resource: a resource that contains information on how to formulate a request to a map. This document includes the CRSs and styles supported and other metadata (including attribution). 
It also specifies how to apply a style to a map resources to get a styled map.

1.2 BBoxSubset 
It specifies how to include a query parameter to subset a styled map using a BBOX, WIDTH, HEIGHT etc as a query parameters. This is a partition that can be input for OGC API Common. Is the OGC API Features BBOX useful here?. Could we have a instant time here?. Clip versus intersect could be problematic in Common (in maps it was "almost" always clipping).

1.3. DatasetMap - OGC API Common - Part 1 (dataset, /map resource at the root)
Defines how to get a map resource from the dataset (or datasets) represented by the services. it will tell the path to get a map resources

1.4. GeoDataResourceSelection - together with 3, collections= query parameters
This is identical from the OGC API Tiles GeoDataResourceSelection and if done adequately, we could share this conformance class with OGC API tiles (or the other way around). (Is this OGC API Common? Part 2)

1.5. GeoDataResourceMap - OGC API Common - Part 2 / OGC Feature - Part 1 (collection connection, /maps resource after {collectionID})
It will define how to specify the a link to a map resource containing a representation of this geospatial data resource (path).

2.1. Time, elevation and other dimensions

3.1. GetFeatureInfo

(In n.mm  n means "Part n" (independent document) and mm means independent conformance class or section)

**Comment by ghobona** [comment]
The **current structure** is shown in the attached screenshot.

![Screenshot 2020-07-14 at 13 36 26](https://user-images.githubusercontent.com/18121038/87426615-6157b580-c5d7-11ea-8405-4fe8a32dc31e.png)

We need to move existing requirements from the old structure to the new structure.

**Comment by joanma747** [comment]
This is the diagram of the new requirements classes for both OGC API - tiles and OGC API - maps

![image](https://user-images.githubusercontent.com/5230444/87884654-0fb48e00-ca10-11ea-9920-53ff4a0557b6.png)

I'm already applying this to the OGC API-maps to get it ready for the OGC API Maps sprint.

**Comment by jerstlouis** [comment]
@joanma747 Is a Tiles Part 2: maps really necessary?

If an API satisfies both the requirements for Tiles Part 1: Core, and those of Maps Part 1: Core, and the GeoData-tileset is associated with a GeoData-map, doesn't that necessarily imply conforming "Map Tiles"?

However how can a Tiles API expose the fact that a tileset is associated with a map (map tiles), or directly with the raw data (raw data tiles)?

And what about when the raw data as stored on the sever is already color-adjusted (A)RGB imagery (e.g. a mosaic)? Can that be considered both a map and the raw data? Is it still the Maps API, if there is no styling capability available? (Are we planning to support .../{collectionId}/map in addition to e.g. .../{collectionId}/map/default ? (I think the 'default' resource directly at /map is convenient).

I believe that re-usable bbox, width and height query parameters (I imagine this is all covered by Maps: Part 2 partition in the diagram) should be defined as a conformance class of Common GeoData, since BBOX and resolution/scale applies to all types of geospatial data. But what resource would you use for display-ready imagery together with that, would that still be /map ? If an implementation of the Coverage API can also support this re-usable BBOX partition conformance class and the same representation/format, you would basically getting the exact same thing from both /coverage?bbox=... and /map?bbox=... .
I think that's good, but which of these resources would be recommended to use in that case? /coverage or /map, or both?

Also for those who have not yet come across it, here is a great demo of both Map and Data Tiles and Coverage API all nicely integrated from CubeWerx at:
https://test.cubewerx.com/cubewerx/cubeserv/demo/ogcapi/Daraa/collections/Daraa_DTED

**Comment by jerstlouis** [comment]
I answered some of my questions in:

https://github.com/opengeospatial/OGC-API-Tiles/issues/43#issuecomment-663338836
