### ISSUE TITLE
Has OGC considered Center Point?

### ISSUE THREAD

**Issue by jeffharrison** [opengeospatial/ogcapi-maps#73]
With respect to Tiles API... has OGC considered use of Center Point? I apologize in advance if this is an ignorant question.

An example of a template from Bing Maps is below...

https://dev.virtualearth.net/REST/v1/Imagery/Map/imagerySet/centerPoint/zoomLevel?mapSize={mapSize}&pushpin={pushpin}&mapLayer={mapLayer}&format={format}&mapMetadata={mapMetadata}&key={BingMapsAPIKey}

**Comment by jerstlouis** [comment]
SWG 2022-07-21: So what is missing in Maps regarding center point, is the ability to specify the extent to be returned as a view center + view range. Suggesting that we require implementations to specify `viewCenter` and `viewRange` as an alternative to a `bbox` or `subset` in the subsetting (partitioning?) conformance class.

Something else that may be related is the ability to specify a `projectionCenter` overriding without requiring a different CRS (see #92).

**Comment by joanma747** [comment]
While the idea is nice I will recommend the use of the term "range" that in coverage means "values" instead of coordinates. Assuming that the idea behind the viewRange is to specify a distance in CRS coordinates, I will recommend term such as viewRadius or viewDistance that immediately suggest a "size in CRS coordinates".

**Comment by joanma747** [comment]
I perfectly understand what you mean. However you have to think this in the context of the OGC vocabulary. "feature" "coverage", "range"; I do not like any of them but this is what was decided. This give us a language to understand each other. If "range" was already used in the CIS context, we need a different word, whatever it is. 

You are right that "viewDistance" could be misinterpreted. Let's forget about this one.

> View radius may not be accurate because it is not a circle (view diameter would be close, if you consider that the circle extends beyond the viewport and you're specifying the diameter that corresponds to the longest viewport dimension).
ViewExtent?

**Comment by jerstlouis** [comment]
@joanma747 

>  This give us a language to understand each other. It will be wrong to change it.

Unfortunately, sometimes I feel like we have a language to misunderstand each other, especially for people not familiar with a wide _range_ of OGC standards, and more importantly, sometimes it may impede adoption / implementation by wider communities and going mainstream. Perhaps some small, iterative steps could be taken over time to make OGC vocabulary more accessible. But that is a separate discussion :)

> ViewExtent?

_viewExtent_ sounds good, but I fear many would assume that a bounding box is expected for such a parameter :)

**Comment by joanma747** [comment]
The combination of center+zoom_level is useful when you cannot predict the size of the view port. For instance I use "center+zoom_level" as a way to set  where our map browser will initiate. Since I cannot predict the size of the user screen (potentially each users will have a different size), I cannot rely on bbox if I want to maintain zoom-level. 

What is the use case in our OGC API maps?. A client that is lazy and do not what to calculate the bbox?. In the past, the client requested a bbox and _believe_ that the server will comply. Now, we have the header with the returned bbox so, in principle, we could imagine a client that never know the bbox "a priori", requests center+zoom_level and read the header to know the bbox only "a posteriori". If we want to support this use case, then, let's do it.

**Comment by jerstlouis** [comment]
> What is the use case in our OGC API maps?. A client that is lazy and do not what to calculate the bbox?

If what the client cares about is a view scale rather than a specific bounding box, it is not a simple calculation so it would be nice to have the ability to specify the center + scale instead of the bounding box in the API.

A zoom level depends on a particular scale set or tile matrix set. A scale does not suffer from the ambiguity of a _view range_ extending as to which dimension of the viewport it refers to (horizontal, vertical, diagonal or widest).

**Comment by jerstlouis** [comment]
SWG 2022-11-10: The group recommends to decide on the following in the next meeting:

- Add a `center` query parameter defaulting to the native CRS (or should it be WGS84)
- Add a `center-crs` query parameter to specify the CRS of the center parameter other than the default
- Add a `scale-denominator` query parameter defining the view scale denominator
- Add a `mmPerPixel` query parameter defining the physical size of the target display pixel (#59)

Everyone present in the core group today were in agreement.

**Comment by jerstlouis** [comment]
`mmPerPixel` doesn't follow the kebab-case rule. Should it be `mm-per-pixel`?

**Comment by joanma747** [comment]
reviewed in a telco
